<?php get_header(); ?>
  <?php if (have_posts()) : while (have_posts()) : the_post(); ?>
    <div class="wb__page-hero legal__hero-bg">
      <h2 class="st__title textured">Terms<br><img class="st__title-wave" src="<?php echo get_stylesheet_directory_uri() ?>/assets/wb__home-wave.png" alt=""></h2>
    </div>

   <div class="rs__ctn wb__page-legal">
     <p>
       This is a legal agreement between "You" (including but not limited to any visitor, user, subscriber, free trial user, or purchaser of any waterboys service whether or not requiring payment of a fee) and waterboys, inc., ("Waterboys") stating the terms that govern your use of the waterboys website (the "Website"). This agreement - together with all updates, additional terms, software licenses, and all of waterboys's rules and policies, including the waterboys privacy policy, all as amended - collectively constitute the "Agreement" between you and waterboys. This is a legally-binding contract between you and waterboys that grants you a limited license to access the website, and to use the media downloads. You must accept and abide by these terms as presented to you: changes, additions, or deletions are not acceptable, and waterboys may refuse access to the website for noncompliance with any part of this agreement. In addition, when using particular services, you may be subject to guidelines or rules or additional terms (which may be posted from time to time) applicable to such services and which are incorporated by reference into the terms of use. All such guidelines or rules are hereby incorporated by reference into the terms of use. Your acceptance of this agreement means that you give consent to waterboys to email you with notices concerning a material change in the terms of this agreement or the services offered through this website. As used herein, "Services" includes any version or type of the waterboys services as well as multimedia downloads or other services provided by waterboys, accessed through the internet and various mediums or devices now known or hereafter developed. You understand and agree that the services may include advertisements and that these advertisements are necessary for waterboys to provide the services.
     </p>
     <p>
       The use of the Website is subject to this Agreement. By accessing this Website, you accept and agree to be bound by this Agreement. If you do not wish to abide by these terms and conditions, please leave the Website now and do not access or use this Website in the future, unless you assume the obligations outlined below.
     </p>
     <p>
       1. COPYRIGHT NOTICE This Website was created by Waterboys. "Waterboys", and the Waterboys logo are trademarks of Waterboys. All trademarks, trade names, company names, slogans, logos, and any other copyright items which can be seen on the Website pages in various contexts are the property of their respective owners. You have no right to copy, distribute or otherwise use them without the prior written consent of the owners. Any use of any trademarks appearing on the Website without the express written consent of the owner of the trademark is strictly prohibited. This Website is copyright 2015 Waterboys Inc. All rights reserved. Any use other than as permitted by these Terms of use, change or duplication of this Website, in whole or in part, without the prior written permission of Waterboys is strictly forbidden.
     </p>
     <p>
       2. INTELLECTUAL PROPERTY RIGHTS AND PERMITTED USES Only you may access the Services using your username and password. The Services available through the Website are the property of Waterboys or its licensors and are protected by copyright and other intellectual property laws. The Services may be used for your personal, non-commercial use only. You agree not to (i) reproduce, record, retransmit, distribute, disseminate, sell, rent, broadcast or circulate any content received through any Service to any third party, (ii) exploit any such content for commercial purposes without the express prior written consent of Waterboys, or (iii) share your password with any third party. You may not make any unauthorized copies of any content obtained through the Services. Because the Services are designed for personal use, you are not allowed to use any automated system for the selection or streaming of files. You further agree to indemnify and hold harmless Waterboys for your failure to comply with this section, and these Terms of Use generally. Waterboys and its licensors retain exclusive ownership of the Services and all intellectual property rights associated therewith. Except as expressly provided herein, you are not granted any rights or license to patents, copyrights, trade secrets or trademarks with respect to the Services or their contents. Waterboys reserves all rights not expressly granted hereunder. You shall promptly notify Waterboys in writing upon your discovery of any unauthorized use or infringement of the Services or their contents or any patent, copyright, trade secret, trademarks or other intellectual property rights of Waterboys or its licensors. The Services contain proprietary information that is protected by copyright laws and international treaty provisions.
     </p>
     <p>
       3. Waterboys expressly disclaims any and all responsibility or liability for any action by you that is contrary to such law(s) and reserves the right to terminate your service immediately for your failure to comply with any such law. Certain content on the Website may not be available to you due to third-party license restrictions pertaining thereto. You understand that the Services may include security components that permit digital materials to be protected, and use of these materials is subject to usage rules set by Waterboys and/or licensors or content providers who provide content to the Service. You agree that you will not attempt to override or circumvent any of the usage rules embedded into the Services, or forming a part of these Terms of Use. In addition, you may not reverse engineer, transcode, decompile, translate, adapt, modify, disassemble or otherwise tamper with any media downloaded from the Website, or circumvent any technology designed to enforce these limitations on use (existing or contemplated). Any unauthorized reproduction, publication, further distribution or public exhibition of the materials provided on the Services, in whole or in part, is strictly prohibited. All rights not expressly granted to you in these Terms of Use are reserved to Waterboys and/or its licensors.
     </p>
     <p>
       4. USER REGISTRATION In consideration of your use of the Services, you represent that you are of legal age to form a binding contract and are not a person barred from receiving services under the laws of Canada or other applicable jurisdictions. You may only open an account for yourself, and not for any other person. You also agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the Service's registration form (such information being the "Registration Data") and (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or Waterboys has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Waterboys has the right to suspend or terminate your account and refuse any and all current or future use of the Service (or any portion thereof), whether paid or not. You acknowledge and agree that the complete privacy of your data and messages transmitted while registering or using the Website cannot be guaranteed. During Waterboys registration, you will select a password and user login Upon successful registration for the Service, you will receive an account designation. You understand and agree that you are solely responsible for maintaining the confidentiality of your account including your password, and are fully responsible for all activities that occur under your account. You agree to (a) immediately notify Waterboys of any unauthorized use of your password or account or any other breach of security, and (b) exit from your account at the end of each session. You agree to notify Waterboys immediately of any unauthorized use of your account or password, or any other breach of security. However, you may be held liable for losses incurred by Waterboys, its third party licensors, or by any other user of or visitor to the Website due to someone else using your Registration Data. No person may use anyone else's unique Registration Data at any time. Waterboys will not be liable for any loss or damage arising from your failure to comply with this Section. In compliance with its Privacy Policy, Waterboys is entitled to collect and analyze data relating to your Registration Data and your use of the Website. You acknowledge and expressly consent to Waterboys accessing, preserving, and disclosing your Registration Data if required to do so by law or in the good faith belief that such access, preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce the Terms of Use; (c) respond to claims that any content on the Website violates the rights of third-parties; (d) respond to your requests for customer service; or (e) protect the rights, property, or personal safety of Waterboys, its users and the public.
     </p>
     <p>
       5. TECHNOLOGY LIMITATIONS AND MODIFICATIONS TO SERVICE Waterboys will make reasonable efforts to keep your account and the Services operational. However, certain technical difficulties or maintenance may, from time to time, result in temporary interruptions. We will make reasonable efforts to notify you at least twenty-four (24) hours in advance of any downtime that we anticipate in advance will exceed one hour. Waterboys also reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, functions and features of the Service(s) with or without notice. Due to contractual or other limitations, from time to time, some video downloads may no longer be available. Waterboys reserves the right to change remove content from availability as multimedia downloads at any time and for any reason. Waterboys shall not be liable to you or to any third party for any of the direct or indirect consequences of any modification, malfunction, suspension, discontinuance of or interruption to or of any of the Services. You understand and agree that the Services are provided "AS-IS" and that Waterboys assumes no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings.
     </p>
     <p>
       6. ACCESS TO WATERBOYS You are responsible for obtaining access to the Services and that access may involve third party fees (such as Internet service provider, cellphone, or other airtime charges). You are responsible for those fees, including fees associated with the display or delivery of advertisements. In addition, you must provide and are responsible for all equipment necessary to access the Service. Special product or service offerings and promotions displayed on the Website are considered no longer valid once they are removed from the Website. Additionally, all offerings, discounts, coupons, and promotions are subject to change or cancellation at any time without notice.
     </p>
   </div>
   <div class="st__bar-ctn">
     <p>Reducing the distance to a water source by 15 minutes results in a 12% increase in school attendance.</p>
   </div>
      <?php endwhile; ?>
      <?php endif ?>
    <?php get_footer(); ?>
